[workspace]
members = ["leptos-fetch"]
resolver = "3"

[workspace.package]
version = "0.3.1"
repository = "https://github.com/zakstucke/leptos-fetch"
license = "MIT"
authors = ["Zak Stucke"]
edition = "2021"
keywords = ["leptos"]
description = "Async query manager for Leptos"
readme = "./leptos-fetch/README.md"
rust-version = "1.80"

[workspace.dependencies]
any_spawner = "0.2"
hydration_context = "0.2" # 0.3
leptos = "0.7" # 0.8.0-alpha

chrono = "0.4"
futures = "0.3"
paste = "1"
parking_lot = "0.12"
send_wrapper = "0.6"
serde = "1"