name: Rust

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main 

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Tests Client
        run: cargo test --all

      - name: Run Tests SSR
        run: cargo test --all --features ssr

      - name: Build wasm
        run: cargo build --target wasm32-unknown-unknown

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings        
