name: Rust

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--cfg erase_components"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-hack
        run: cargo install cargo-hack --locked

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo hack clippy --lib --feature-powerset --all-targets -- -D warnings

      - name: Run Lib Tests
        run: cargo hack test --lib --feature-powerset

      - name: Run All Tests and Examples
        run: cargo test --all --all-features

      - name: Build wasm
        run: cargo hack build --feature-powerset --no-dev-deps --exclude-features=ssr --target wasm32-unknown-unknown
